import { Link } from 'react-router-dom'

export default function Research() {
  return (
    <div className="flex justify-center">
      <main className="container mx-auto max-w-[700px] px-6 py-10">
        {/* Back Button */}
        <Link to="/" className="back-link text-blue-500">
          ← back
        </Link>

        {/* Research & Projects Section */}
        <section className="mt-6">
          <h2 className="text-xl font-bold mb-3 text-black-600">Research & Projects</h2>
          
          {/* Hackathon Projects */}
          <div className="mb-4">
            <div className="flex justify-between items-center">
              <h3 className="text-md font-semibold mb-1 text-blue-600">Hackathon Winning Projects</h3>
              <span className="text-blue-600 font-semibold">2025, 2020</span>
            </div>
            <div className="ml-4">
              <div className="mb-4">
                <span className="font-bold">1st Place Datathon 2025 ETH (Orderfox Challenge) 🏆</span>
                <p>Developed a Multi-Agent RAG chatbot to answer supply chain queries by combining semantic search (via a vector database built from Orderfox's web-scraped dataset) and exact keyword filtering (via a NoSQL store generated by an LLM agent). <span className="text-gray-500">(OpenAI, ChromaDB, LangGraph, FastAPI, React)</span> <a href="https://www.datathon.ai/" className="small-link" target="_blank" rel="noreferrer">link</a></p>
              </div>
              <div className="mb-2">
                <span className="font-bold">1st Place BitsxLaMarató 2020 🏆</span>
                <p>Created a telegram bot that classified Covid19 cough audios using Deep Learning <span className="text-gray-500">(PyTorch)</span> <a href="https://github.com/CarlOwOs/Apolo-COVID-cough-predictor" className="small-link" target="_blank" rel="noreferrer">link</a></p>
              </div>
            </div>
          </div>

          {/* ICCV Attendance */}
          <div className="mb-4">
            <div className="flex justify-between items-center">
              <h3 className="text-md font-semibold mb-1 text-blue-600">Chosen Attendee at ICCV Paris 2023</h3>
              <span className="text-blue-600 font-bold">2023</span>
            </div>
            <p className="ml-4">Attended ICCV in representation of Mediapro to discuss our SOTA object tracking methods with industry leaders. <span className="text-gray-500">(CV, Multi Object Tracking, Tiny Object Detection)</span></p>
          </div>

          {/* Video & Image Segmentation */}
          <div className="mb-4">
            <div className="flex justify-between items-center">
              <h3 className="text-md font-semibold mb-1 text-blue-600">Video & Image Segmentation for a Pharmaceutical Lab</h3>
              <span className="text-blue-600 font-bold">2021</span>
            </div>
            <p className="ml-4">Segmented videos and images of zebrafish larvae's hearts, with metric extraction and drug toxicity classification. Developed business model for the product. <span className="text-gray-500">(Image Processing, Deep Learning, Agile)</span></p>
          </div>

          {/* Spotify Project */}
          <div className="mb-4">
            <div className="flex justify-between items-center">
              <h3 className="text-md font-semibold mb-1 text-blue-600">Spotify Explicit Content Predictor</h3>
              <span className="text-blue-600 font-bold">2020</span>
            </div>
            <p className="ml-4">Developed an R-based application that was able to extract any song's Spotify Track Features and predict whether it would have explicit content or not using Logistic Regression and MLPs. <span className="text-gray-500">(R, OpenRefine, API)</span> <a href="https://github.com/megaelius/SWERING/blob/master/Abad-Fuentes-Marti/report.pdf" className="small-link" target="_blank" rel="noreferrer">link</a></p>
          </div>
        </section>

        {/* Image section */}
        <section className="mt-20">
          <div className="w-full h-auto max-w-[500px] mx-auto">
            <img src="/assets/img/wip.png" alt="Work in Progress" className="w-full h-auto" />
          </div>
        </section>
      </main>
    </div>
  )
}
